Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # admin page
    path('admin/', admin.site.urls),
    path('users/', include("users.urls")),
    # index page
    path('', include('blogs.urls')),

]

blogs/urls.py
from django.urls import path
from . import views

app_name = "blogs"

urlpatterns = [
    # Home page
    path("", views.home, name="home"),
    # Page for each blog post
    path("<int:post_id>/", views.post, name="post"),
    # Page to create a new post
    path("new_post/", views.new_post, name="new_post"),
    # Page to edit one post
    path("edit_entry/<int:post_id>/", views.edit_entry, name="edit_entry"),
    # Page to delete a post
    path("delete_post/<int:post_id>/", views.delete_post, name="delete_post"),
]

users/urls.py
"""Define URL patterns for users"""

from django.urls import path, include
from . import views

app_name = "users"

urlpatterns = [
    # Include default  auth urls
    path("", include("django.contrib.auth.urls")),
    # Registration page 
    path('register/', views.register, name='register')
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class BlogPost(models.Model):

    """Une class qui contient le model d'un blog post"""
    title = models.CharField(max_length=100)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'posts'

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import BlogPost


class PostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ["title", "text"]
        labels = {"tile": "", "text": "Entry:"}
        widgets = {"text": forms.Textarea(attrs={"cols": 80})}


# class EntryForm(forms.ModelForm):
#     class Meta:
#         model = BlogPost
#         fields = ["text"]
#         lables = {"text": "Entry:"}
#         widgets = {"text": forms.Textarea(attrs={"cols": 80})}

blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import BlogPost
from .forms import PostForm  # , EntryForm

# Create your views here.


def home(request):
    """Show all blogs at the index"""
    blogs = BlogPost.objects.order_by("-date_added")
    context = {"blogs": blogs}
    return render(request, "blogs/home.html", context)


def post(request, post_id):
    """Show a single post and all its text"""
    post = BlogPost.objects.get(id=post_id)
    entries = post.text
    context = {"post": post, "entries": entries}
    return render(request, "blogs/post.html", context)


@login_required
def new_post(request):
    """Add a new post"""
    if request.method != "POST":
        # No data submitted, create a blank form
        form = PostForm()

    else:
        # Post data submitted; process data
        form = PostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return redirect("blogs:home")

    # Display a blank or invalid form
    context = {"form": form}
    return render(request, "blogs/new_post.html", context)


@login_required
def edit_entry(request, post_id):
    """Edit an existing entry """
    post = BlogPost.objects.get(id=post_id)
    text = post.text
    check_topic_owner(request, post)

    if request.method != "POST":
        # Initial request; pre=fill form with the current entry
        form = PostForm(instance=post)
    else:
        # POST data submitted; process data.
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("blogs:home") #, post_id=post.id)

    context = {"post": post, "text": text, "form": form}
    return render(request, "blogs/edit_entry.html", context)

@login_required
def delete_post(request, post_id):
    """Delete an existing post"""
    post = BlogPost.objects.get(id=post_id)

    if request.method == 'POST':
        post.delete()
        return redirect('blogs:home')

    context = {"post": post}
    return render(request, 'blogs/delete_post.html', context)

def check_topic_owner(request, post):
    if post.owner != request.user:
        raise Http404

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
    """Register a new user"""
    if request.method != 'POST':
        # Display blank registration form 
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page
            login(request, new_user)
            return redirect('blogs:home')

    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1", shrink-to-fit=no">
  <title>Simple Blog</title>

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 border">

    <a class="navbar-brand" href="{% url 'blogs:home'%}">
      Home </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button> 
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blogs:new_post'%}">
            New post</a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text"}">Hello, {{ user.username }}</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
          </li>
        {% endif %}  
      </ul>
    </div> 
  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>

</html>

blogs/templates/blogs/delete_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h3><a href="{% url 'blogs:post' post.id %}">{{ post }}</a></a></h3>
{% endblock page_header %}

{% block content %}
<div class="card mb-3">
  <h4 class="card-header">
    Delete post
  </h4>
</div>

<form method="post" action="{% url 'blogs:delete_post' post.id %}" class="form">
  <h3>Are you sure you want to delete this post ?</h3>
  {% csrf_token %}
  {% buttons %}
    <button name="submit" class="btn btn-outline-danger">Yes, Delete post</button>
    <a class="btn btn-outline-secondary" href="{% url 'blogs:post' post.id %}">Cancel</a>
  {% endbuttons %} 
  </form> 
    
{% endblock content %}

blogs/templates/blogs/edit_entry.html
{% extends 'blogs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
  <h3><a href="{% url 'blogs:post' post.id %}">{{ post }}</a></h3>
{% endblock page_header %}

{% block content %}
<form action="{% url 'blogs:edit_entry' post.id %}" method="post" class="form">
  {% csrf_token %} 
  {% bootstrap_form form %}
  {% buttons %}
    <button name="submit" class="btn btn-primary">Save changes</button>
    <a class="btn btn-outline-secondary" href="{% url 'blogs:post' post.id %}">Cancel</a>
  {% endbuttons %}
</form>

{% endblock content %}

blogs/templates/blogs/home.html
{% extends 'blogs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
  <h3>#100DaysofCode</h3>
{% endblock page_header %}
{% block content %}

  {% for blog in blogs %}
    <div class="card mb-3">
        <h4 class="card-header">
          <center><a href="{% url 'blogs:post' blog.id %}">{{ blog.title }}</a></center>
          <center><small> {{ blog.date_added|date:"Y-m-d" }}</small></center>
        </h4>
        <div class="card-body">
          <center>
            {{ blog.text|truncatewords:30 }}
          </center>
        </div>
        {% buttons %}
          <center>
            <a class="btn btn-outline-primary" href="{% url 'blogs:post' blog.id %}">Read more</a>
          </center>
        {% endbuttons %}  
    </div>

  {% empty %}
      <p>There are no entries for this topic yet</p>
  {% endfor %}

{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends 'blogs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
  <h3>Add a new post</h3>
{% endblock page_header %}

{% block content %}

  <form method="post" action="{% url 'blogs:new_post' %}" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button name="submit" class="btn btn-primary">Add post</button>
        <a class="btn btn-outline-secondary" href="{% url 'blogs:home' %}">Cancel</a>
      {% endbuttons %}
  </form>

{% endblock content %}

blogs/templates/blogs/post.html
{% extends 'blogs/base.html' %} 
{% load bootstrap4 %}

{% block page_header %}
  <span style="position: absolute; right:170px;">
    <a style="color: red" href="{% url 'blogs:delete_post' post.id %}">delete post</a>
  </span>
  <h3>
    <center><a href="{% url 'blogs:home' %}">{{ post }}</a></center>
  </h3>

{% endblock page_header %}

{% block content %}

<div class="card mb-3">
  <div class="card-body">
    {{ entries|linebreaks }}
  </div>
</div>
{% buttons %}
  {% if post.owner == request.user %}
    <a class="btn btn-primary" href="{% url 'blogs:edit_entry' post.id %}">Edit entry</a>
  {% endif %}
{% endbuttons %}

{% endblock content %}